<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="test.expectedResponseTest"
    errors="1" failures="0" hostname="" id="" package="expectedResponseTest" skipped="0"
    tests="1" time="0.2950" timestamp="">
  
    <testcase name="API Test - GET" classname="test.expectedResponseTest" time="0.2950" assertions="1">

    
    <error message="newData is not defined" type="error"><![CDATA[
    ReferenceError: newData is not defined
    at Object.API Test - GET (/Users/dschaich/Documents/nw_sample/e2e/test/expectedResponseTest.js:15:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ]]></error>
    
    </testcase>
  

  
    <system-err>
       ✖ ReferenceError
   newData is not defined

    Error location:
    /Users/dschaich/Documents/nw_sample/e2e/test/expectedResponseTest.js:
    ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
     13 |     const data = await response.json();
     14 |     console.log(data);
     15 |     await browser.assert.includes(newData, &#39;auth&#39;); 
     16 |   },
     17 |   after: async function(browser) {
    ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

    Stack Trace :
    at Object.API Test - GET (/Users/dschaich/Documents/nw_sample/e2e/test/expectedResponseTest.js:15:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    </system-err>
  

    

  
  </testsuite>
</testsuites>
